# Generated by Django 5.0.6 on 2024-07-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Ap', '0004_alter_productos_options_boleta_boletaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletaitem',
            name='boleta',
        ),
        migrations.RemoveField(
            model_name='boletaitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
        migrations.DeleteModel(
            name='BoletaItem',
        ),
    ]
