# Generated by Django 5.0.6 on 2024-07-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Ap', '0005_remove_boletaitem_boleta_remove_boletaitem_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
