# Generated by Django 5.0.6 on 2024-07-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_Ap', '0006_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('horario', models.CharField(max_length=100)),
            ],
        ),
    ]
